#ifndef CANOPEN_TM4C_COMMONS_H_
#define CANOPEN_TM4C_COMMONS_H_

/* CAN Controller Definitions*/
#define CAN_BIT_RATE 1000000U
#define CAN_LOOPBACK_MODE_ENABLED false



/*TODO: Replace this value with your specific NODE ID*/
#ifndef CO_DESIRED_NODE_ID
#define CO_DESIRED_NODE_ID 0x03
#endif

/* Definitions for CANopen LEDS
 * TODO: Replace PORT and PIN number with your application use*/
#define CAN_LEDS_PERIPH SYSCTL_PERIPH_GPIOF
#define CAN_LEDS_PORT GPIO_PORTF_BASE
#define CAN_RED_LED_PIN GPIO_PIN_1
#define CAN_GREEN_LED_PIN GPIO_PIN_3

#define CAN_SYSCTL_PERIPH SYSCTL_PERIPH_CAN0
#define CAN_SYSCTL_PERIPH_GPIO SYSCTL_PERIPH_GPIOB
#define CAN_PORT GPIO_PORTB_BASE
#define CAN_GPIO_PINS GPIO_PIN_4 | GPIO_PIN_5
#define CAN_RX_PIN GPIO_PB4_CAN0RX
#define CAN_TX_PIN GPIO_PB5_CAN0TX
#define CAN_BASE CAN0_BASE
#define CAN_INT INT_CAN0


#endif /* CANOPEN_TM4C_COMMONS_H_ */
